-- 01_CREATE_TABLES

DROP TABLE IF EXISTS claims;

CREATE TABLE claims (
    id TEXT,
    patientid TEXT,
    providerid TEXT,
    primarypatientinsuranceid TEXT,
    secondarypatientinsuranceid TEXT,
    departmentid TEXT,
    patientdepartmentid TEXT,
    diagnosis1 TEXT,
    diagnosis2 TEXT,
    diagnosis3 TEXT,
    diagnosis4 TEXT,
    diagnosis5 TEXT,
    diagnosis6 TEXT,
    diagnosis7 TEXT,
    diagnosis8 TEXT,
    referringproviderid TEXT,
    appointmentid TEXT,
    currentillnessdate TEXT,
    servicedate TEXT,
    supervisingproviderid TEXT,
    status1 TEXT,
    status2 TEXT,
    statusp TEXT,
    outstanding1 TEXT,
    outstanding2 TEXT,
    outstandingp TEXT,
    lastbilleddate1 TEXT,
    lastbilleddate2 TEXT,
    lastbilleddatep TEXT,
    healthcareclaimtypeid1 TEXT,
    healthcareclaimtypeid2 TEXT
);

DROP TABLE IF EXISTS patients;

CREATE TABLE patients (
    id TEXT,
    birthdate TEXT,
    deathdate TEXT,
    ssn TEXT,
    drivers TEXT,
    passport TEXT,
    prefix TEXT,
    first TEXT,
    middle TEXT,
    last TEXT,
    suffix TEXT,
    maiden TEXT,
    marital TEXT,
    race TEXT,
    ethnicity TEXT,
    gender TEXT,
    birthplace TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    county TEXT,
    fips TEXT,
    zip TEXT,
    lat TEXT,
    lon TEXT,
    healthcare_expenses TEXT,
    healthcare_coverage TEXT,
    income TEXT
);